### ISSUE TITLE
Nouns Style Minter

### ISSUE THREAD

**Issue by lyaunzbe** [ArtBlocks/artblocks-contracts#185]
nouns style auction for an entire project, ie artist does a small mint size collection like 32 mints, each mint auctions for 15min and the visual outcome is visible during that time period, so it’s like an 8hr event essentially. params would be configurable 

[add more...]

**Comment by lyaunzbe** [comment]
copying over some comments from @Jbern16 in slack

> Noun style minter would be really awesome, further, an entire vertical to funding public art on an ongoing basis would be so based, even more based if in partnership with a non profit like saveartspace.
https://mirror.xyz/noun40.eth/D9UkttH3KPdTKXXzhY-ujFML4G1y0knnXodxzbCbfo8

**Comment by jakerockland** [comment]
L F G
