### ISSUE TITLE
Engine Flex contract type should be added

### ISSUE THREAD

**Issue by lyaunzbe** [ArtBlocks/artblocks-contracts#282]
not critical/breaking, but adding core version + type would be very beneficial 
https://github.com/ArtBlocks/artblocks-contracts/blob/main/contracts/GenArt721CoreV3.sol#L158

**Comment by jakerockland** [comment]
@lyaunzbe I may be getting confused on what is suggested here, but any reason not to just send quick PR for this (is this just a one-line change)?

**Comment by lyaunzbe** [comment]
@jakerockland yep exactly that was the plan! just added here last friday afternoon for visibility/to remember to do it (flex pr had already merged into main). Was going to do it at some point today, but anyone else can feel free to as well 👍
