### ISSUE TITLE
Consider bumping Solidity to 0.8.16 for all impacted files pre-relase of V3

### ISSUE THREAD

**Issue by jakerockland** [ArtBlocks/artblocks-contracts#293]
cc @ryley-o for your thoughts on this

**Comment by ryley-o** [comment]
I see no reason not to, based on ref: https://blog.soliditylang.org/2022/09/08/solidity-0.8.17-release-announcement/

**Comment by jakerockland** [comment]
> I see no reason not to, based on ref: https://blog.soliditylang.org/2022/09/08/solidity-0.8.17-release-announcement/

Roger that, my thinking was the same. !vibe

**Comment by jakerockland** [comment]
:shipit:

**Comment by jakerockland** [comment]
We did this. Closing. cc @ryley-o
