### ISSUE TITLE
Incorporate smart-contract architecture diagram into top-level README

### ISSUE THREAD

**Issue by jakerockland** [ArtBlocks/artblocks-contracts#387]
A rough outline of our current smart contract design architecture [lives here in Drive](https://docs.google.com/drawings/d/1yqn8mtlfSO-njecn-WCNDIapt9hBcwwJvjjVpFTyC2w) and should be cleaned up and added to this repo at some point. 

May want to consider using this fancy markdown diagram setup: https://twitter.com/diegohaz/status/1590043504428077056?s=51&t=ZCnED_j_CrR7NTVhw8H-tg

For now, a screenshot of current Google Drawing version of the diagram is included here inline in this ticket for reference. 

<img width="940" alt="Screenshot 2022-11-15 at 12 49 01 PM" src="https://user-images.githubusercontent.com/8602661/202012065-dae55f3c-c48d-459f-8ba6-441658a25f5a.png">

**Comment by ryley-o** [comment]
I believe this was implemented here, so closing: https://github.com/ArtBlocks/artblocks-contracts/commit/9d2734a92306e93466ee2f08f083537035c946ff
