### ISSUE TITLE
Art Blocks Engine (on-chain) suggestion

### ISSUE THREAD

**Issue by maxgmer** [ArtBlocks/artblocks-contracts#418]
Would be cool if when we mint we could send an optional integer into a smart contract and then get that integer in tokenData from our artwork.

1. **Integer is small enough to be on-chain.**
2. **Adds a lot of customizability**.
(Because integer can be anything (e.g age, in-game class (e.g. warrior, mage etc), whatever a project needs).

This will make many more projects consider Art Blocks Engine as a smart contract solution.
And (probably) easy to implement.

**Comment by jakerockland** [comment]
@maxgmer this is definitely a possible/tractable customization to be made – happy to discuss in context of a specific Engine release. 

cc @cooper-temple

**Comment by jakerockland** [comment]
Closing this out per offline conversation w/ @maxgmer
