### ISSUE TITLE
Incorporate architecture diagrams in the documentation within this repo 

### ISSUE THREAD

**Issue by jakerockland** [ArtBlocks/artblocks-contracts#508]
@ryley-o an idea for a future polish week

**Comment by ryley-o** [comment]
good call, documented internally as a polish task.
https://app.asana.com/0/1203634050572702/1204101460059685/f

**Comment by ryley-o** [comment]
While #537 does add a minter suite diagram, I think more diagrams would be good. For example, Royalty Registry override contracts, Curation/Dependency registry contracts, and likely some others (perhaps more detailed minter diagrams) are all nice to haves, that fall under this issue.
Cc @jakerockland
