### ISSUE TITLE
Clear natspec documentation around new event emission convention

### ISSUE THREAD

**Issue by lyaunzbe** [ArtBlocks/artblocks-contracts#714]
With the minter-suite re-architecture, we are making the decision to decouple a lot of shared logic into libraries that minters can pull in. However, with this new design, both ACL checks and event emissions cannot live in the library, but rather must live in the top level minter functions that are calling the shared logic in the library functions. This generally looks like so:

```
function sampleFunction(
.....
) external {
        _sampleACLCheck(...);
        SampleLib.sampleFunction(...);
        emit ConfigValueSet(...);
}
```
Let's add documentation around this to make it clear for future minter implementations/dev's working with these minters.

**Comment by ryley-o** [comment]
we were able to move events into the libraries after some iteration with our auditor prior to release, so marking this as resolved 🥳
